HumbleMathsWeb/Controllers/MathsController.cs
using System;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

using HumbleMaths.Calculators.Interpolation;
using HumbleMaths.LinearSystemSolvers;
using HumbleMaths.Parsers;
using HumbleMaths.Tools;
using HumbleMathsWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace HumbleMathsWeb.Controllers {
    public class MathsController : Controller {
        private readonly MatrixParser _parser = new MatrixParser();
        private readonly GaussSolver _solver = new GaussSolver();
        private readonly FunctionValuesGenerator _functionValuesGenerator = new FunctionValuesGenerator();
        private readonly IFunctionInterpolator _lagrangeInterpolator = new LagrangeInterpolator();

        public IActionResult Index() {
            return View();
        }

        [Route("/Maths/Gauss")]
        public IActionResult Gauss() {
            return View();
        }

        [HttpPost("/Maths/Gauss", Name = "matrix")]
        public IActionResult Gauss(MatrixModel model) {
            var matrix = model.Input;

            if (matrix == null) {
                return View();
            }

            var matrixModel = new MatrixModel {
                Solution = null,
                Stopwatch = new Stopwatch()
            };

            matrixModel.Stopwatch.Start();

            try {
                var system = _parser.ParseMatrix(matrix);
                matrixModel.System = system;

                var solution = _solver.SolveSystem(system);
                matrixModel.Solution = solution;
            }
            catch {
                matrixModel.Stopwatch.Stop();
                return View(matrixModel);
            }

            matrixModel.Stopwatch.Stop();
            return View(matrixModel);
        }

        [Route("/Maths/Integral")]
        [HttpPost("/Maths/Integral")]
        public IActionResult Integral(IntegralModel model) {
            if (!ParseFields(model)) {
                return View(model);
            }

            if (model.Precision < 0) {
                return View(model);
            }

            var lambdaParser = new LambdaParser();

            try {
                var function = lambdaParser.ParseLambda(model.FunctionExpression);
                model.Func = function;
            }
            catch {
                return View(model);
            }

            try {
                var function = lambdaParser.ParseLambda(model.IntegralFunctionExpression);
                model.IntegralFunc = function;
            }
            catch {
                // ignored
            }

            var found = model.Methods.TryGetValue(model.MethodAsText, out var method);

            if (!found) {
                return View(model);
            }

            model.IntegralCalculator = method;

            var stopwatch = new Stopwatch();
            stopwatch.Start();

            model.CalculationFinished = false;

            var task = Task.Run(() => {
                (model.IntegralValue, model.PartsAmount) =
                    method.Calculate(x => model.Func(x), model.Start, model.End, model.Precision);

                model.CalculationFinished = true;
            });

            task.Wait(20000);

            stopwatch.Stop();
            model.CalculationTime = stopwatch.Elapsed;

            return View(model);
        }

        private static bool ParseFields(IntegralModel model) {
            if (!double.TryParse(model.StartAsText, NumberStyles.Any,
                CultureInfo.InvariantCulture, out var start)) {
                return false;
            }

            if (!double.TryParse(model.EndAsText, NumberStyles.Any,
                CultureInfo.InvariantCulture, out var end)) {
                return false;
            }

            if (!double.TryParse(model.PrecisionAsText, NumberStyles.Any,
                CultureInfo.InvariantCulture, out var precision)) {
                return false;
            }

            model.Start = start;
            model.End = end;
            model.Precision = precision;

            return true;
        }

        [Route("/Maths/Lagrange")]
        [HttpPost("/Maths/Lagrange")]
        public IActionResult Lagrange(LagrangeModel model) {
            if (model == null) {
                return View();
            }

            try {
                var start = double.Parse(model.Start, CultureInfo.InvariantCulture);
                var end = double.Parse(model.End, CultureInfo.InvariantCulture);
                var step = double.Parse(model.Step, CultureInfo.InvariantCulture);

                if ((end - start) / step > 10000) {
                    throw new ArgumentException();
                }

                if (model.InputWay == "func") {
                    InterpolateByFunction(_functionValuesGenerator, start, end, step);
                }
                else {
                    InterpolateByPoints();
                }

                var interpolationFunction = _lagrangeInterpolator
                    .InterpolateByPoints(model.InterpolationNodes);

                model.InterpolatedValues = _functionValuesGenerator
                    .GenerateValues(interpolationFunction, start, end, step)
                    .ToList()
                    .AsReadOnly();
            }
            catch {
                // ignored
            }

            return View(model);

            void InterpolateByFunction(FunctionValuesGenerator valuesGenerator, double start, double end, double step) {
                var func = new LambdaParser().ParseLambda(model.FunctionExpression);

                model.Values = valuesGenerator.GenerateValues(func, start, end, step)
                    .ToList()
                    .AsReadOnly();

                var interpolationStep = double.Parse(model.InterpolationStep, CultureInfo.InvariantCulture);

                if ((end - start) / interpolationStep > 500) {
                    throw new ArgumentException();
                }

                model.InterpolationNodes = valuesGenerator
                    .GenerateValues(func, start, end, interpolationStep)
                    .ToList()
                    .AsReadOnly();
            }

            void InterpolateByPoints() {
                model.InterpolationNodes = model.InputValues
                    .Split('\n')
                    .Where(s => !string.IsNullOrWhiteSpace(s))
                    .Select(s => s.Trim().Split(' ')
                        .Select(n => double.Parse(n, CultureInfo.InvariantCulture))
                        .ToList())
                    .Select(n => (n[0], n[1]))
                    .ToList()
                    .AsReadOnly();
            }
        }
    }
}

HumbleMathsWeb/Views/IntegratorContoller/Index.cshtml
@using System.Globalization
@model IntegratorModel
@{
    ViewBag.Title = "Лабораторная работа 4";
    Layout = "_Layout";
}

<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>
    $(document).ready(() => {
        const data = [];

        @for (var i = 0; i < Model.Results.Count; i++) {
            var result = Model.Results[i];

            @($"const actualX{i} = [")
            @(string.Join(", ", result
                .Select(val => $"{val.x.ToString("F10", CultureInfo.InvariantCulture)}")))
            @("];")

            @($"const actualY{i} = [")
            @(string.Join(", ", result
                .Select(val => $"{val.y.ToString("F10", CultureInfo.InvariantCulture)}")))
            @("];")
        }

        data.push({ type: "scattergl", mode: "line", x: actualX0, y: actualY0 });
        data.push({ type: "scattergl", mode: "line", x: actualX1, y: actualY1 });
        data.push({ type: "scattergl", mode: "line", x: actualX2, y: actualY2 });

        Plotly.plot('graph', data, { showlegend: false });
    });

    function upload() {
        const fileReader = new FileReader();
        fileReader.onload = function() {
            const xhr = new XMLHttpRequest();
            xhr.open('post', "");
            xhr.setRequestHeader("Content-type", "text/plain");
            const result = window.atob(fileReader.result.replace("data:text/plain;base64,", ""));
            xhr.send(result);
            const input = result;
            console.log(input);

            $("#inputValues").val(input);
        };
        fileReader.readAsDataURL(document.getElementById("file").files[0]);
    }
</script>

<div class="row justify-content-between">
    <div class="col-7">
        <h4>Решение ОДУ методом Адамса и методом Эйлера</h4>
    </div>
    <div class="col-1">
        <a asp-area="" asp-controller="Maths" asp-action="Index"
           class="btn btn-dark">
            Назад
        </a>
    </div>
</div>
<hr/>

<div class="container-fluid">
    <form asp-action="Index" method="post" id="form" asp-antiforgery="true">
        <div class="alert-danger" asp-validation-summary="All"></div>

        <div class="form-group">
            <label style="margin: 10px">Функция $f(x, y)$</label>
            <input type="text" asp-for="FFunctionExpression" name="FFunctionExpression" class="form-control" id="function" placeholder="2 * x, cos(x), pow(x, 3) * 4, etc.">
        </div>
        <div class="form-group">
            <label style="margin: 10px">Функция $y(x)$</label>
            <input type="text" asp-for="YFunctionExpression" name="YFunctionExpression" class="form-control" placeholder="2 * x, cos(x), pow(x, 3) * 4, etc.">
        </div>
        <div class="form-group">
            <label style="margin: 10px">Предполагаемая функция $F(x)$</label>
            <input type="text" asp-for="RealFunctionExpression" name="RealFunctionExpression" class="form-control" placeholder="2 * x, cos(x), pow(x, 3) * 4, etc.">
        </div>

        <div class="form-group form-row">
            <div class="col">
                <label style="margin: 10px">$x_0$</label>
                <input type="text" asp-for="CaucheX" class="form-control">
            </div>
            <div class="col">
                <label style="margin: 10px">$y_0$</label>
                <input type="text" asp-for="CaucheY" class="form-control">
            </div>
            <div class="col">
                <label style="margin: 10px">Размер шага</label>
                <input type="text" asp-for="StepLength" class="form-control">
            </div>
            <div class="col">
                <label style="margin: 10px">Количество шагов</label>
                <input type="text" asp-for="StepAmount" class="form-control">
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Найти решение</button>
        </div>
    </form>
</div>
<div class="container-fluid">
    <div id="graph"></div>
</div>

@section scripts {
    <environment names="Development">
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
    </environment>
}